name: BankPlugin
version: '${project.version}'
main: ru.komap.bankplugin.BankPlugin
api-version: '1.19'

commands:
  deposit:
    description: Положить алмазы на счет
    usage: /deposit <количество>
  withdraw:
    description: Снять алмазы со счета
    usage: /withdraw <количество>
  transfer:
    description: Перевести алмазы другому игроку
    usage: /transfer <игрок> <количество>
  balance:
    description: Узнать свой баланс
    usage: /balance
  me:
    description: Default minecraft me
    usage: /me <action>
  try:
    description: Try to do something!
    usage: /try <action>
  disaster:
    description: Summons disaster
    usage: /disaster
  minusfps:
    description: aboba
    usage: /minusfps <player>