name: BankPlugin
version: '2.0-SNAPSHOT'
main: ru.komap.bankplugin.BankPlugin
api-version: '1.21'

commands:
  deposit:
    description: Положить алмазы на счет
    usage: /deposit <количество>
  withdraw:
    description: Снять алмазы со счета
    usage: /withdraw <количество>
  transfer:
    description: Перевести алмазы другому игроку
    usage: /transfer <игрок> <количество>
  balance:
    description: Узнать свой баланс
    usage: /balance